name: iltgo
description: A traffic app.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  tflite: ^1.1.2
  cupertino_icons: ^1.0.4
  font_awesome_flutter: '>= 4.7.0'
  cloud_firestore: ^3.1.15
  firebase_auth: ^3.3.18
  fluttertoast: ^8.0.9
  firebase_core: ^1.17.0
  google_sign_in: ^5.3.1
  google_fonts: ^3.0.1
  flutter_staggered_grid_view: 0.6.1
  random_string: ^2.3.1
  image_picker: ^0.8.5+3
  get: ^4.6.5
  http: ^0.13.4
  firebase_storage: ^10.2.16
  random_color: ^1.0.5
  flutter_swipable: ^1.2.1
  swipe_cards: ^1.0.0
  splashscreen: ^1.3.5
  flutter_randomcolor: ^1.0.12
  rename: ^2.0.1
  path_provider: ^2.0.11
  file_picker: ^4.6.1
  video_player: ^2.4.4
  readmore: ^2.1.0
  flutter_feather_icons: ^2.0.0+1
  multiavatar: ^0.1.5
  flutter_tindercard: ^0.2.0
  swipeable_card_stack: ^0.0.5
  swipe_to: ^1.0.2
  spring_button: ^2.0.0
  flutter_animated_dialog: ^2.0.1
  auto_size_text: any
  percent_indicator: any
  google_maps_flutter: ^2.1.12
  google_maps_flutter_web: ^0.4.0+2
  google_place: ^0.4.7
  geolocator: ^9.0.1
  flutter_polyline_points: ^1.0.0
  flutter_svg: ^1.1.4
  fab_circular_menu: ^1.0.2
  flutter_rating_bar: ^4.0.1
  flutter_rating_stars: ^1.0.3+4
  flip_card: ^0.6.0
  lottie: ^1.4.2
  dartz: ^0.10.1
  location: ^4.4.0
  alert_dialog: ^1.0.1
  camera: ^0.10.0+3
  quiz_view: ^1.0.5
  sqflite: ^2.0.3+1
  shared_preferences: ^2.0.15
  carousel_slider: ^4.1.1
  provider: ^6.0.3
  flutter_riverpod: ^2.0.0
  dio: ^4.0.6
  rflutter_alert: ^2.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  image_path: "assets/iLTGoLogo.png"
  android: true
  ios: true

flutter:
  assets:
    - img/
    - img/002.png
    - assets/model_unquant.tflite
    - assets/labels.txt
    - trafficsignsimg/
    - assets/
    - assets/animassets/13177-location.json
    - assets/mapicons/
    - assets/animassets/

  uses-material-design: true

fonts:
  - family: Ranga
    fonts:
      - asset: asset\fonts/Ranga-Regular.ttf
      - asset: asset\fonts/Ranga-Bold.ttf
        weight: 700
  - family: Arimo
    fonts:
      - asset: asset\fonts/Arimo-Regular.ttf
      - asset: asset\fonts/Arimo-Italic.ttf
        style: italic
      - asset: asset\fonts/Arimo-Bold.ttf
        weight: 700
