// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWMTolQeUD_mDqgNcymTreKYM_qaNNE7E',
    appId: '1:869083543955:android:e0d9d12f964706af011066',
    messagingSenderId: '869083543955',
    projectId: 'iltgoaccounts',
    storageBucket: 'iltgoaccounts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvtSRQZZuN068747leuN-qGgKLo4gLRuw',
    appId: '1:869083543955:ios:bd43a8c65eb7ab77011066',
    messagingSenderId: '869083543955',
    projectId: 'iltgoaccounts',
    storageBucket: 'iltgoaccounts.appspot.com',
    androidClientId:
        '869083543955-kq5gc6u06tue3ebpncud4du804hbcecp.apps.googleusercontent.com',
    iosClientId:
        '869083543955-j903mucql32a45733v2f5lrm47kvhgnh.apps.googleusercontent.com',
    iosBundleId: 'com.example.iltgov2',
  );
}
